name: "Feedback"
description: "Feedback on the document"
labels:
  - feedback
  - needs-review
body:
  - type: input
    id: name
    validations:
      required: true
    attributes:
      label: "Your Name"
  - type: input
    id: org
    validations:
      required: false
    attributes:
      label: "Your Organization (optional)"
  - type: textarea
    id: use-case-restrictions
    validations:
      required: false
    attributes:
      label: "Should the Code state that if a use case is not specifically called out above, it is restricted? Or should it be more open?"
  - type: textarea
    id: revise-process
    validations:
      required: false
    attributes:
      label: "What should the process to revise the Code look like?"
  - type: textarea
    id: new-freq
    validations:
      required: false
    attributes:
      label: "How frequently should we add new use cases? Is an every-6-months update sufficient? Every 3 months?"
  - type: textarea
    id: specify-criteria
    validations:
      required: false
    attributes:
      label: "Do we need to specify more here in the Code in terms of criteria for approving new use cases (or modifying existing ones), or can we put it in the form (which we have yet to create)?"
